# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:59
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='span',
            name='user',
        ),
        migrations.AlterField(
            model_name='span',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
